name: Deploy StorageApp Backend

on:
    workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ vars.SSH_USER }}
      REMOTE_APP_DIR: ${{ vars.REMOTE_APP_DIR }}

    steps:
      # 1. Setup SSH key and known_hosts
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add server host key so SSH does not ask for confirmation
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      # 2. Deploy to remote server
      - name: Deploy backend on EC2
        run: |
          ssh "${SSH_USER}@${SSH_HOST}" 'bash -s' << EOF
            set -e

            echo "Starting deployment for production..."

            echo "Switching to project directory..."
            cd "$REMOTE_APP_DIR"

            echo "Getting latest code..."
            git pull

            echo "Installing dependencies..."
            npm ci --no-audit --no-fund

            echo "Restarting backend..."
            pm2 reload storageApp

            echo "Backend Deployed Successfully..."
          EOF
